services:
  qs-postgres:
    image: postgres:17
    container_name: qs-postgres
    environment:
      POSTGRES_USER: churn
      POSTGRES_PASSWORD: churnpass
      POSTGRES_DB: churn
    volumes:
      - qs-pgdata:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    networks:
      - qs-data
    restart: unless-stopped

volumes:
  qs-pgdata:
    name: qs-pgdata

networks:
  qs-data:
    name: qs-data
